### ISSUE TITLE
Bilibili看不了了啊！！！

### ISSUE THREAD

**Issue by pockem** [taxigps/xbmc-addons-chinese#110]
能进去但是无法播放 而且安装的时候经常显示 beautifulsoup4无法安装 keyboard chinese无法安装

**Comment by pockem** [comment]
而且我发现很多插件 在KODI升级后 都是依赖库什么问题 无法安装 不知道有没有专门的依赖库的下载包？ 现在只能用老版本的XBMC KODI 希望能获得解决办法啊 就指望他看B站了

**Comment by pockem** [comment]
应该是插件-依赖里面的那几个

**Comment by pockem** [comment]
就指望KODI看B站了 因为我的盒子不太兼容官方的APP 哎哎哎怎么办啊 之前都好的 突然就看不了了

**Comment by pockem** [comment]
这是错误日志 我随便播放的一个
23:35:52 T:3568  NOTICE: [xbmcswift2] Request for "/video/video%2Fav4841009%2Findex_1.html/0/0/" matches rule for function "play_video"
23:35:52 T:3568   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'xml.parsers.expat.ExpatError'>
                                            Error Contents: not well-formed (invalid token): line 1, column 0
                                            Traceback (most recent call last):
                                              File "C:\Users\Mampachi\AppData\Roaming\Kodi\addons\plugin.video.bilibili\addon.py", line 254, in <module>
                                                plugin.run()
                                              File "C:\Users\Mampachi\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "C:\Users\Mampachi\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "C:\Users\Mampachi\AppData\Roaming\Kodi\addons\plugin.video.bilibili\addon.py", line 244, in play_video
                                                playlist = bili.get_video_urls(url, False)
                                              File "C:\Users\Mampachi\AppData\Roaming\Kodi\addons\plugin.video.bilibili\resources\lib\bilibili.py", line 248, in get_video_urls
                                                return self._parse_urls(page_content, need_subtitle)
                                              File "C:\Users\Mampachi\AppData\Roaming\Kodi\addons\plugin.video.bilibili\resources\lib\bilibili.py", line 87, in _parse_urls
                                                doc = minidom.parseString(content)
                                              File "D:\program files (x86)\Kodi\system\python\Lib\xml\dom\minidom.py", line 1928, in parseString
                                                return expatbuilder.parseString(string)
                                              File "D:\program files (x86)\Kodi\system\python\Lib\xml\dom\expatbuilder.py", line 940, in parseString
                                                return builder.parseString(string)
                                              File "D:\program files (x86)\Kodi\system\python\Lib\xml\dom\expatbuilder.py", line 223, in parseString
                                                parser.Parse(string, True)
                                            ExpatError: not well-formed (invalid token): line 1, column 0
                                            -->End of Python script error report<--
23:35:52 T:3484   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.bilibili/video/video%2Fav4841009%2Findex_1.html/0/0/
23:35:52 T:3484   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.bilibili/video/video%2Fav4841009%2Findex_1.html/0/0/) failed
23:35:52 T:464  NOTICE: [xbmcswift2] Request for "/videos/4841009/" matches rule for function "show_video_list"

**Comment by zhuchenwang** [comment]
I also have the similar problem on my raspberry pi 3. I guess the sign code and appkey are expired. I fixed it myself by update the sign code and appkey.

**Comment by celeron533** [comment]
bilibili新版的android app在盒子上无法用遥控器操作。
老版本的[bilibili白]倒是可用，可以暂时用这个缓解一下。

**Comment by pockem** [comment]
Hi,zhuchenwang. Would u like to teach me how to fix this problem? I'm just a greenhand on KODI ;;;;;;;;;

**Comment by pockem** [comment]
bilibili 盒子安卓版很不好用 超清没声音 白版遥控器操控不了 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;

**Comment by celeron533** [comment]
我在天猫魔盒1S+上解码器都手工调整过了，否则要么是无法播放，要么就是播放卡顿

**Comment by pockem** [comment]
我是魔盒2 反正超清肯定是没声音的 高清有些没声音 最近好像的确是不能放。。

**Comment by taxigps** [comment]
@osfans

**Comment by pockem** [comment]
@jiangming1399

**Comment by jiangming1399** [comment]
Bilibili开启了API校验 这需要一会来改代码。

**Comment by jiangming1399** [comment]
已修复，待Merge

**Comment by pockem** [comment]
@jiangming1399 万分感谢！辛苦大神了！！！
