### ISSUE TITLE
X86-64 kodi.17 ubuntu.16.04下字幕插件均出现错误

### ISSUE THREAD

**Issue by antikan** [taxigps/xbmc-addons-chinese#148]
log中大量下面的内容：

18:10:34.131 T:140042357942016   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute '_base'
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/service.subtitles.zimuzu/service.py", line 13, in <module>
                                                from bs4 import BeautifulSoup
                                              File "/home/kodi/.kodi/addons/script.module.beautifulsoup4/lib/bs4/__init__.py", line 30, in <module>
                                                from .builder import builder_registry, ParserRejectedMarkup
                                              File "/home/kodi/.kodi/addons/script.module.beautifulsoup4/lib/bs4/builder/__init__.py", line 311, in <module>
                                                from . import _html5lib
                                              File "/home/kodi/.kodi/addons/script.module.beautifulsoup4/lib/bs4/builder/_html5lib.py", line 57, in <module>
                                                class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
                                            AttributeError: 'module' object has no attribute '_base'
                                            -->End of Python script error report<--
18:10:34.165 T:140042064328448   ERROR: GetDirectory - Error getting plugin://service.subtitles.zimuzu/?action=search&languages=Chinese%20(Simple)%2cEnglish&preferredlanguage=Chinese%20(Simple)

18:10:50.346 T:140042357942016   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute '_base'
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/service.subtitles.163sub/service.py", line 12, in <module>
                                                from bs4 import BeautifulSoup
                                              File "/home/kodi/.kodi/addons/script.module.beautifulsoup4/lib/bs4/__init__.py", line 30, in <module>
                                                from .builder import builder_registry, ParserRejectedMarkup
                                              File "/home/kodi/.kodi/addons/script.module.beautifulsoup4/lib/bs4/builder/__init__.py", line 311, in <module>
                                                from . import _html5lib
                                              File "/home/kodi/.kodi/addons/script.module.beautifulsoup4/lib/bs4/builder/_html5lib.py", line 57, in <module>
                                                class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
                                            AttributeError: 'module' object has no attribute '_base'
                                            -->End of Python script error report<--
18:10:50.378 T:140042475374336   ERROR: GetDirectory - Error getting plugin://service.subtitles.163sub/?action=search&languages=Chinese%20(Simple)%2cEnglish&preferredlanguage=Chinese%20(Simple)
18:10:53.908 T:140042357942016   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute '_base'
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/service.subtitles.subhd/service.py", line 12, in <module>
                                                from bs4 import BeautifulSoup
                                              File "/home/kodi/.kodi/addons/script.module.beautifulsoup4/lib/bs4/__init__.py", line 30, in <module>
                                                from .builder import builder_registry, ParserRejectedMarkup
                                              File "/home/kodi/.kodi/addons/script.module.beautifulsoup4/lib/bs4/builder/__init__.py", line 311, in <module>
                                                from . import _html5lib
                                              File "/home/kodi/.kodi/addons/script.module.beautifulsoup4/lib/bs4/builder/_html5lib.py", line 57, in <module>
                                                class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
                                            AttributeError: 'module' object has no attribute '_base'
                                            -->End of Python script error report<--
18:10:53.937 T:140042206926592   ERROR: GetDirectory - Error getting plugin://service.subtitles.subhd/?action=search&languages=Chinese%20(Simple)%2cEnglish&preferredlanguage=Chinese%20(Simple)

**Comment by snowf0x** [comment]
android下也出现错误
18:51:31 T:18446744072530372104   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'encode'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.subhd/service.py", line 265, in <module>
                                                Search(item)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.subhd/service.py", line 93, in Search
                                                version = it.find_all("span", class_=re.compile("label"))[-1].get('title').encode('utf-8')
                                            AttributeError: 'NoneType' object has no attribute 'encode'
                                            -->End of Python script error report<--
18:51:31 T:18446744072538223264   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://service.subtitles.subhd/?action=search&languages=Chinese%2cEnglish&preferredlanguage=English

**Comment by taxigps** [comment]
@snowf0x subhd字幕插件升级到1.0.13
@antikan 你这个不是字幕插件问题，log信息显示是script.module.beautifulsoup4出问题。

**Comment by snowf0x** [comment]
@taxigps 感谢！

**Comment by antikan** [comment]
@taxigps 系统有python2 3，默认python2，以前用kodi 16没问题的，17下出现这问题。
