### ISSUE TITLE
人人美剧坏了

### ISSUE THREAD

**Issue by pjrobertson** [taxigps/xbmc-addons-chinese#198]
应该把人人美剧删除，因为现在没用了。 他在用的URL （`https://api.rr.tv/v3plus/video/indexInfo`) 现在404了

```
02:27:14.517 T:1182790400   DEBUG: Fetch URL :https://api.rr.tv/v3plus/video/indexInfo, with data: None
02:27:14.520 T:1182790400   DEBUG: ('loading url', 'https://api.rr.tv/v3plus/video/indexInfo')
02:27:14.809 T:1182790400   ERROR: Traceback (most recent call last):
02:27:14.810 T:1182790400   ERROR:   File "/snip/.kodi/addons/plugin.video.rrmj/resources/lib/common.py", line 61, in GetHttpData
02:27:14.810 T:1182790400   ERROR:     response = urllib2.urlopen(req, timeout=3)
02:27:14.810 T:1182790400   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
02:27:14.813 T:1182790400   ERROR:     return opener.open(url, data, timeout)
02:27:14.813 T:1182790400   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 435, in open
02:27:14.813 T:1182790400   ERROR:     response = meth(req, response)
02:27:14.813 T:1182790400   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
02:27:14.813 T:1182790400   ERROR:     'http', request, response, code, msg, hdrs)
02:27:14.813 T:1182790400   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 473, in error
02:27:14.814 T:1182790400   ERROR:     return self._call_chain(*args)
02:27:14.814 T:1182790400   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
02:27:14.814 T:1182790400   ERROR:     result = func(*args)
02:27:14.814 T:1182790400   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
02:27:14.814 T:1182790400   ERROR:     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
02:27:14.815 T:1182790400   ERROR: HTTPError: HTTP Error 404: Not Found
```

**Comment by taxigps** [comment]
@jindaxia 人人美剧还维护升级吗？

**Comment by jindaxia** [comment]
目前版本应该不维护了,APP接口全变了,以后有空再维护 就重新发一个了
