### ISSUE TITLE
zimuku 1.1.4 debug

### ISSUE THREAD

**Issue by YK-Samgo** [taxigps/xbmc-addons-chinese#270]
不知道关闭的PR #269 里你还能看见不，所以新开一个issue。

可能你是没测试到一些特定编码的东西，我这边有几个视频，不打开line 28 和 29 那两行就会在line 343 getPlayingFile()的时候挂掉。。。python这日了狗的编码问题呀
```
-->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.UnicodeEncodeError'>
Error Contents: 'ascii' codec can't encode characters in position 42-43: ordinal not in range(128)
Traceback (most recent call last):
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.zimuku/service.py", line 343, in <module>
        item['file_original_path'] = urllib.unquote(xbmc.Player().getPlayingFile().decode('utf-8'))  # Full path of a playing file
    File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/encodings/utf_8.py", line 16, in decode
UnicodeEncodeError: 'ascii' codec can't encode characters in position 42-43: ordinal not in range(128)
-->End of Python script error report<--
```

**Comment by YK-Samgo** [comment]
另外，要加.sup字幕格式的话，还需要加在service.py的259行，可以考虑把这些变量摘出来放到单独的module里，避免hard code。
`line259:    exts = ( ".srt", ".sub", ".smi", ".ssa", ".ass" )`
->
`line259:    exts = ( ".srt", ".sub", ".smi", ".ssa", ".ass", ".sup" )`

**Comment by taxigps** [comment]
已更新到1.1.5
