### ISSUE TITLE
人人美剧 Api 调用错误

### ISSUE THREAD

**Issue by bao3** [taxigps/xbmc-addons-chinese#90]
##这是部分代码

```

21:24:49 T:2593125248  NOTICE: Fetch URL :http://api2.rrmj.tv/v2/video/search, with data: rows=20&page=1&cat=%E6%81%90%E6%80%96
21:24:49 T:2593125248   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('results',)
                                            Traceback (most recent call last):
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.rrmj/default.py", line 6, in <module>
                                                plugin.run()
                                              File "/var/lib/kodi/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "/var/lib/kodi/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 315, in _dispatch
                                                listitems = self.finish(listitems)
                                              File "/var/lib/kodi/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py", line 493, in finish
                                                self.add_items(items)
                                              File "/var/lib/kodi/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py", line 409, in add_items
                                                _items = [self._listitemify(item) for item in items]
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.rrmj/path.py", line 132, in search
                                                for one in c_list["data"]["results"]:
                                            KeyError: ('results',)
                                            -->End of Python script error report<--
21:24:49 T:3024379904   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
21:24:49 T:2593125248    INFO: Python script stopped
21:24:49 T:2593125248   DEBUG: Thread LanguageInvoker 2593125248 terminating
21:24:49 T:2507142016   DEBUG:  WaitOnScriptResult - plugin exited prematurely - terminating
21:24:49 T:3024379904   ERROR: GetDirectory - Error getting plugin://plugin.video.rrmj/search/cat_%E6%81%90%E6%80%96/page_1
21:24:49 T:3024379904   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.rrmj/search/cat_%E6%81%90%E6%80%96/page_1) failed
21:24:49 T:3024379904   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.rrmj/cat/)
21:24:49 T:3024379904   DEBUG:   ParentPath = [plugin://plugin.video.rrmj/]
21:24:49 T:3024379904   DEBUG: Loading items: 9, directory: plugin://plugin.video.rrmj/cat/ sort method: 0, ascending: false
21:24:49 T:2593125248  NOTICE: Thread BackgroundLoader start, auto delete: false

```

**Comment by taxigps** [comment]
@jindaxia

**Comment by jindaxia** [comment]
已确认，人人美剧API新增了两个验证字段 用于防止非法调用。正在想办法破解

**Comment by kaynim** [comment]
0.0.7版修复了吗？尝试后发先仍然报错。

**Comment by taxigps** [comment]
0.1.0修复

**Comment by Yxnt** [comment]
最新的版本支持吗？
