### ISSUE TITLE
人人美剧0.0.6均无法正常使用

### ISSUE THREAD

**Issue by kaynim** [taxigps/xbmc-addons-chinese#91]
kodi 15.2  ，之前使用0.0.4版本插件可以正常访问，升级到0.0.6之后点击分类、搜索均报错。降级到0.0.4之后也无法正常播放了。

错误日志如下：

6:16:48 T:123145308819456  NOTICE: Fetch URL :http://api2.rrmj.tv/v2/video/indexInfo, with data: None
16:16:50 T:123145307209728 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
16:16:50 T:123145307209728  NOTICE: [xbmcswift2] Request for "/cat/" matches rule for function "category"
16:16:51 T:123145307209728 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
16:16:51 T:123145307209728  NOTICE: [xbmcswift2] Request for "/search/cat_%E7%BD%AA%E6%A1%88/page_1" matches rule for function "search"
16:16:51 T:123145307209728  NOTICE: Fetch URL :http://api2.rrmj.tv/v2/video/search, with data: rows=20&page=1&cat=%E7%BD%AA%E6%A1%88
16:16:51 T:123145307209728   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('results',)
                                            Traceback (most recent call last):
                                              File "/Users/Kaynim/Library/Application Support/Kodi/addons/plugin.video.rrmj/default.py", line 6, in <module>
                                                plugin.run()
                                              File "/Users/Kaynim/Library/Application Support/Kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "/Users/Kaynim/Library/Application Support/Kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 315, in _dispatch
                                                listitems = self.finish(listitems)
                                              File "/Users/Kaynim/Library/Application Support/Kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py", line 493, in finish
                                                self.add_items(items)
                                              File "/Users/Kaynim/Library/Application Support/Kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py", line 409, in add_items
                                                _items = [self._listitemify(item) for item in items]
                                              File "/Users/Kaynim/Library/Application Support/Kodi/addons/plugin.video.rrmj/path.py", line 132, in search
                                                for one in c_list["data"]["results"]:
                                            KeyError: ('results',)
                                            -->End of Python script error report<--
16:16:52 T:140735271112704   ERROR: GetDirectory - Error getting plugin://plugin.video.rrmj/search/cat_%E7%BD%AA%E6%A1%88/page_1
16:16:52 T:140735271112704   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.rrmj/search/cat_%E7%BD%AA%E6%A1%88/page_1) failed
16:16:52 T:123145307209728 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
16:16:52 T:123145307209728  NOTICE: [xbmcswift2] Request for "/cat/" matches rule for function "category"
16:16:53 T:123145318096896   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
16:16:53 T:123145318096896   ERROR: CCurlFile::Open failed with code 0 for http://feeds.xbmc.org/xbmc

**Comment by taxigps** [comment]
同 #90

**Comment by kaynim** [comment]
辛苦！
